<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacompras [
 <!ELEMENT listacompras (venta)+>
 <!ELEMENT venta (ventacredito | ventainmediata)*>
 <!ELEMENT ventacredito (fechafinpago*,cantidad)>
 <!ELEMENT ventainmediata (cantidad,divisa*)>
 <!ELEMENT fechafinpago (#PCDATA)>
 <!ELEMENT cantidad (#PCDATA)>
 <!ELEMENT divisa (#PCDATA)>
]>
    <listacompras>
        <venta>
            <ventacredito>
                <fechafinpago>22-10-2021</fechafinpago>
                <cantidad>21000</cantidad>
            </ventacredito>
        </venta>
        <venta>
            <ventainmediata>
                <cantidad>1800</cantidad>
                <divisa>euros</divisa>
            </ventainmediata>
        </venta>
        <venta>
            <ventacredito>
                <cantidad>21000</cantidad>
            </ventacredito>
        </venta>
    </listacompras>